// export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_ONE_SUCCESS = 'GET_NEWS_ONE_SUCCESS';

// export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
// export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
